apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krr-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: krr-chart
  namespace: krr
roleRef:
  kind: ClusterRole
  name: krr-clusterrole
  apiGroup: rbac.authorization.k8s.io
